Updates to AIO and UI.  See details.
* Added DISABLE_RPKI variable to AIO container to disable RPKI for LAB/isolated environments
* Fixed issue where docker log openbmp_aio would show mysql access denied error.
* Upgraded RPKI to use 2.22
* Fixed issue with docker AIO using localhost where sometimes it wouldn't work.
* Updated the UI to build 293

diff --git a/aio/scripts/run_all_in_one b/aio/scripts/run_all_in_one
--- a/aio/scripts/run_all_in_one
+++ b/aio/scripts/run_all_in_one
@@ -18,7 +18,6 @@ OPENBMP_DB_NAME=${OPENBMP_DB_NAME:="openBMP"}
 GROUP_ID=${GROUP_ID:="openbmp-mysql-consumer"}
 ADMIN_ID=${ADMIN_ID:="collector"}
 
-
 source /etc/default/openbmpd
 
 #
@@ -123,28 +122,23 @@ done
 #
 # Update kafka fqdn/hostname
 #
-DOCKER_HOST_IP=$(ip route | grep default | head -1 | awk '{ print $3}')
 if [[ ${API_FQDN:-""} = "" ]]; then
-    echo "ERROR: API_FQDN not set using docker run -e API_FQDN=<value>, cannot proceed."
-    exit 1
-else
-    if [[ ${API_FQDN} == "localhost" ]]; then
-        API_FQDN="docker-localhost"
+    API_FQDN=localhost
 
-    elif [[ ${API_FQDN} == "127.0.0.1" ]]; then
-        API_FQDN="docker-localhost"
-
-    elif [[ ${API_FQDN} == "::1" ]]; then
-        API_FQDN="docker-localhost"
-    fi
-
-    # Update the hosts file
-    echo "$DOCKER_HOST_IP         docker-localhost" >> /etc/hosts
-
-    # Update kafka config
-    sed -i -r "s/^[#]*advertised.host.name=.*/advertised.host.name=${API_FQDN}/" \
-            /usr/local/kafka/config/server.properties
+elif [[ ${API_FQDN} == "::1" ]]; then
+    API_FQDN="localhost"
 fi
+
+# If API_FQDN doesn't resolve, then use localhost
+ping -c 1 $API_FQDN
+if [[ $? -eq 2 ]]; then
+    echo "NOTICE: $API_FQDN cannot be resolved or reached.  Using 'localhost' instead."
+    API_FQDN=localhost
+fi
+
+# Update kafka config
+sed -i -r "s/^[#]*advertised.host.name=.*/advertised.host.name=${API_FQDN}/" \
+        /usr/local/kafka/config/server.properties
 
 # Update the etc hosts file
 if [[ -f /config/hosts ]]; then
@@ -190,12 +184,21 @@ if [[ $(ps -ef | grep kafka  | grep -v grep | wc -l) -ne 2 ]]; then
 fi
 
 # Start the rpki validator
-if [[ -d /config/rpki/tal ]]; then
-    cp -f /config/rpki/tal/* /usr/local/rpki/conf/tal/
+if [[ ${DISABLE_RPKI:-""} != "" ]]; then
+    if [[ -d /config/rpki/tal ]]; then
+        cp -f /config/rpki/tal/* /usr/local/rpki/conf/tal/
+    fi
+
+    /usr/local/rpki/rpki-validator.sh start
+
+    # Add RPKI cron entries
+     sed  -i '/rpki/d' /etc/crontab
+     echo "12 1 * * * root /usr/local/rpki/rpki-validator.sh start > /dev/null" >> /etc/crontab
+     echo "1 */2   * * *   root     /usr/local/bin/rpki_validator.py  -u openbmp -p ${OPENBMP_DB_PASSWORD} -s localhost:8080 localhost > /var/log/rpki-validator.log" >> /etc/crontab
+else
+    # Remove rpki cron entries
+    sed  -i '/rpki/d' /etc/crontab
 fi
-
-/usr/local/rpki/rpki-validator.sh start
-
 
 # Start openbmpd and wait - openbmpd runs in foreground
 pkill openbmpd
